/**:
  ros__parameters:
    kd_xy: 0.3
    Kd_y: 0.3
    kd_yaw: 0.5
    kd_z: 0.4
    ki_xy: 0.05
    Ki_y: 0.05
    ki_yaw: 0.0
    ki_z: 0.1
    kp_xy: 0.8
    Kp_y: 0.8
    kp_yaw: 1.0
    kp_z: 1.0
    arena_x_max: 2.0
    arena_x_min: -2.0
    arena_y_max: 2.0
    arena_y_min: -2.0
    max_z: 2.0
    scale_x: 0.8071796061782703
    scale_y: 0.8071796061782703
    trim_x: 0.0
    trim_y: 0.0
    target_x: 1.0
    target_y: 0.0
    circle_radius: 0.15
    circle_speed: 0.15
    lookat_x: 1.0
    lookat_y: 0.0
    use_real_drone: true
